/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kutuphane_gui_2;

import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author mobyrktr
 */
public class admin_panel extends javax.swing.JFrame {
    DefaultTableModel model;
    /**
     * Creates new form admin_panel
     * @throws java.sql.SQLException
     * @throws java.text.ParseException
     */
    public admin_panel() throws SQLException, ParseException {
        initComponents();
        addUserFrame.setSize(408, 320);
        cezaGosterFrame.setSize(792, 315);
        deleteUserFrame.setSize(589, 381);
        allUsersFrame.setSize(582, 371);
        model = (DefaultTableModel) tb_cezalar.getModel();
        cezalariGor();
    }
    
    public void cezalariGor() throws ParseException, SQLException
    {
        Odunc_Islemleri o = new Odunc_Islemleri();
        Kitap_Islemleri k = new Kitap_Islemleri();
        ArrayList<ArrayList> cezalar = o.tumCezalariVer();
        
        for(ArrayList ceza : cezalar)
        {
            int kitap_id = Integer.valueOf(ceza.get(2).toString());
            String tckn = ceza.get(1).toString();
            String isim = ceza.get(0).toString();
            String kitap_adi = k.getBookName(kitap_id);
            String verilme_tarihi = o.getVerilmeTarihi(kitap_id, tckn);
            int ceza_gun = Integer.valueOf(ceza.get(3).toString());
            String ceza_bedel = String.valueOf(ceza_gun * 0.5) + "TL";
            Object[] eklenecek = {tckn, isim, kitap_adi, verilme_tarihi, ceza_gun, ceza_bedel};
            model.addRow(eklenecek);
        }
    }
    
    public void silinecekleriEkle()
    {
        try 
        {
            model = (DefaultTableModel)tb_sil.getModel();
            model.setRowCount(0);
            Kullanici_Islemleri k = new Kullanici_Islemleri();
            ArrayList<ArrayList> kullanicilar = k.getAllUsers();
            for(ArrayList kullanici: kullanicilar)
            {
                String tckn = kullanici.get(0).toString();
                String ad = kullanici.get(1).toString();
                String soyad = kullanici.get(2).toString();
                Object[] eklenecekler = {tckn, ad, soyad};
                model.addRow(eklenecekler);
            }
        } 
        
        catch (SQLException ex) 
        {
            Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void tumKullanicilar()
    {
        try 
        {
            model = (DefaultTableModel)tb_users.getModel();
            model.setRowCount(0);
            Kullanici_Islemleri k = new Kullanici_Islemleri();
            ArrayList<ArrayList> kullanicilar = k.getAllUsers();
            for(ArrayList kullanici: kullanicilar)
            {
                String tckn = kullanici.get(0).toString();
                String ad = kullanici.get(1).toString();
                String soyad = kullanici.get(2).toString();
                Object[] eklenecekler = {tckn, ad, soyad};
                model.addRow(eklenecekler);
            }
        } 
        
        catch (SQLException ex) 
        {
            Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addUserFrame = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_tckn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_soyad = new javax.swing.JTextField();
        btn_kayit = new javax.swing.JButton();
        pwfield = new javax.swing.JPasswordField();
        lbl_mesaj = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf_ad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cezaGosterFrame = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_cezalar = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        deleteUserFrame = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_sil = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbl_sil_mesaj = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        allUsersFrame = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_users = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        btn_add_user = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        addUserFrame.setTitle("Kullanıcı Ekleme Ekranı");
        addUserFrame.setLocation(new java.awt.Point(500, 200));
        addUserFrame.setResizable(false);
        addUserFrame.setSize(new java.awt.Dimension(408, 300));
        addUserFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                addUserFrameWindowClosing(evt);
            }
        });

        jLabel2.setText("Soyadı:");

        jLabel3.setText("TC Kimlik:");

        jLabel4.setText("Parola:");

        btn_kayit.setText("Kullanıcı Ekle");
        btn_kayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitActionPerformed(evt);
            }
        });

        jLabel1.setText("Adı:");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/go_back.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout addUserFrameLayout = new javax.swing.GroupLayout(addUserFrame.getContentPane());
        addUserFrame.getContentPane().setLayout(addUserFrameLayout);
        addUserFrameLayout.setHorizontalGroup(
            addUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addUserFrameLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(addUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addUserFrameLayout.createSequentialGroup()
                        .addComponent(btn_kayit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addUserFrameLayout.createSequentialGroup()
                        .addComponent(lbl_mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
            .addGroup(addUserFrameLayout.createSequentialGroup()
                .addGroup(addUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addUserFrameLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(addUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(addUserFrameLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pwfield, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addUserFrameLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_tckn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addUserFrameLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addUserFrameLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(addUserFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addUserFrameLayout.setVerticalGroup(
            addUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUserFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(addUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_tckn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(lbl_mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_kayit)
                .addContainerGap())
        );

        cezaGosterFrame.setLocation(new java.awt.Point(320, 200));
        cezaGosterFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                cezaGosterFrameWindowClosing(evt);
            }
        });

        tb_cezalar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TC Kimlik", "İsim", "Kitap Adı", "Verilme Tarihi", "Gün", "Ceza Bedeli"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_cezalar);
        if (tb_cezalar.getColumnModel().getColumnCount() > 0) {
            tb_cezalar.getColumnModel().getColumn(0).setResizable(false);
            tb_cezalar.getColumnModel().getColumn(1).setResizable(false);
            tb_cezalar.getColumnModel().getColumn(1).setPreferredWidth(150);
            tb_cezalar.getColumnModel().getColumn(2).setResizable(false);
            tb_cezalar.getColumnModel().getColumn(3).setResizable(false);
            tb_cezalar.getColumnModel().getColumn(4).setResizable(false);
            tb_cezalar.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/go_back.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cezaGosterFrameLayout = new javax.swing.GroupLayout(cezaGosterFrame.getContentPane());
        cezaGosterFrame.getContentPane().setLayout(cezaGosterFrameLayout);
        cezaGosterFrameLayout.setHorizontalGroup(
            cezaGosterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cezaGosterFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cezaGosterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addGroup(cezaGosterFrameLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cezaGosterFrameLayout.setVerticalGroup(
            cezaGosterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cezaGosterFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        deleteUserFrame.setTitle("Kullanıcı Silme Ekranı");
        deleteUserFrame.setLocation(new java.awt.Point(450, 200));
        deleteUserFrame.setResizable(false);
        deleteUserFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                deleteUserFrameWindowClosing(evt);
            }
        });

        tb_sil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TC Kimlik", "Ad", "Soyad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tb_sil);
        if (tb_sil.getColumnModel().getColumnCount() > 0) {
            tb_sil.getColumnModel().getColumn(0).setResizable(false);
            tb_sil.getColumnModel().getColumn(1).setResizable(false);
            tb_sil.getColumnModel().getColumn(2).setResizable(false);
        }

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel12.setText("Ad:");

        jButton1.setText("Kullanıcı Sil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/go_back.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout deleteUserFrameLayout = new javax.swing.GroupLayout(deleteUserFrame.getContentPane());
        deleteUserFrame.getContentPane().setLayout(deleteUserFrameLayout);
        deleteUserFrameLayout.setHorizontalGroup(
            deleteUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteUserFrameLayout.createSequentialGroup()
                .addGroup(deleteUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteUserFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))
                    .addGroup(deleteUserFrameLayout.createSequentialGroup()
                        .addGroup(deleteUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(deleteUserFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel14)
                                .addGap(127, 127, 127)
                                .addGroup(deleteUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(deleteUserFrameLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_sil_mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(deleteUserFrameLayout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        deleteUserFrameLayout.setVerticalGroup(
            deleteUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteUserFrameLayout.createSequentialGroup()
                .addGroup(deleteUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteUserFrameLayout.createSequentialGroup()
                        .addContainerGap(31, Short.MAX_VALUE)
                        .addGroup(deleteUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(deleteUserFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lbl_sil_mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        allUsersFrame.setTitle("Tüm Kullanıcılar");
        allUsersFrame.setLocation(new java.awt.Point(450, 200));
        allUsersFrame.setResizable(false);
        allUsersFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                allUsersFrameWindowClosing(evt);
            }
        });

        tb_users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TC Kimlik", "Ad", "Soyad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tb_users);
        if (tb_users.getColumnModel().getColumnCount() > 0) {
            tb_users.getColumnModel().getColumn(0).setResizable(false);
            tb_users.getColumnModel().getColumn(1).setResizable(false);
            tb_users.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/go_back.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout allUsersFrameLayout = new javax.swing.GroupLayout(allUsersFrame.getContentPane());
        allUsersFrame.getContentPane().setLayout(allUsersFrameLayout);
        allUsersFrameLayout.setHorizontalGroup(
            allUsersFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allUsersFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(allUsersFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                    .addGroup(allUsersFrameLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        allUsersFrameLayout.setVerticalGroup(
            allUsersFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, allUsersFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yönetici Ekranı");
        setLocation(new java.awt.Point(500, 200));

        btn_add_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add_user.png"))); // NOI18N
        btn_add_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_userActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete_user.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/show_all_users.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/quit.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close_app.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/banned.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel6.setText("   Kullanıcı Ekle");

        jLabel7.setText("    Kullanıcı Sil");

        jLabel8.setText(" Tüm Kullanıcılar");

        jLabel9.setText("   Cezaları Gör");

        jLabel10.setText("     Çıkış Yap");

        jLabel11.setText(" Programı Kapat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_add_user, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add_user, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10))
                    .addComponent(jLabel11))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_userActionPerformed
        this.setVisible(false);
        addUserFrame.setVisible(true);
    }//GEN-LAST:event_btn_add_userActionPerformed

    private void btn_kayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitActionPerformed
        Kullanici_Islemleri k = new Kullanici_Islemleri();
        String ad = tf_ad.getText();
        String soyad = tf_soyad.getText();
        String tc = tf_tckn.getText();
        String parola = String.valueOf(pwfield.getPassword());

        if(tc.length() != 11)
        {
            lbl_mesaj.setForeground(Color.red);
            lbl_mesaj.setText("TC Kimlik 11 haneli olmalıdır.");
        }

        else
        {
            k.addUsers(ad, soyad, tc, parola);
            lbl_mesaj.setForeground(Color.green);
            lbl_mesaj.setText("Kullanıcı başarıyla eklendi.");
        }
    }//GEN-LAST:event_btn_kayitActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
           addUserFrame.setVisible(false);
           this.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void addUserFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_addUserFrameWindowClosing
        addUserFrame.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_addUserFrameWindowClosing

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        login_screen l = new login_screen();
        this.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
        cezaGosterFrame.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        cezaGosterFrame.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void cezaGosterFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cezaGosterFrameWindowClosing
        cezaGosterFrame.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_cezaGosterFrameWindowClosing

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        silinecekleriEkle();
        lbl_sil_mesaj.setText("");
        this.setVisible(false);
        deleteUserFrame.setVisible(true);        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int silinecek = tb_sil.getSelectedRow();
        if(model.getRowCount() == 0)
        {
            lbl_sil_mesaj.setForeground(Color.red);
            lbl_sil_mesaj.setText("Tabloda hiç kullanıcı yok.");
        }
        
        else
        {
            if(silinecek == -1)
            {
                lbl_sil_mesaj.setForeground(Color.red);
                lbl_sil_mesaj.setText("Önce tablodan bir seçim yapmalısınız.");
            }
            else
            {
                try {
                    Kullanici_Islemleri k = new Kullanici_Islemleri();
                    Odunc_Islemleri o = new Odunc_Islemleri();
                    String tckn = model.getValueAt(silinecek, 0).toString();
                    if(!o.kitapAlmisMi(tckn))
                    {    
                        k.deleteUsers(tckn);
                        silinecekleriEkle();
                        lbl_sil_mesaj.setForeground(Color.green);
                        lbl_sil_mesaj.setText("Silme işlemi başarılı.");
                    }
                    
                    else
                    {
                        lbl_sil_mesaj.setForeground(Color.red);
                        lbl_sil_mesaj.setText("Kullanıcının kitap(ları) iade etmesi gerekiyor.");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteUserFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_deleteUserFrameWindowClosing
        deleteUserFrame.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_deleteUserFrameWindowClosing

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String ad = jTextField1.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(model);
        tb_sil.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ad, 1));
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tumKullanicilar();
        this.setVisible(false);
        allUsersFrame.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        deleteUserFrame.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        allUsersFrame.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void allUsersFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_allUsersFrameWindowClosing
        allUsersFrame.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_allUsersFrameWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new admin_panel().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(admin_panel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame addUserFrame;
    private javax.swing.JFrame allUsersFrame;
    private javax.swing.JButton btn_add_user;
    private javax.swing.JButton btn_kayit;
    private javax.swing.JFrame cezaGosterFrame;
    private javax.swing.JFrame deleteUserFrame;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_mesaj;
    private javax.swing.JLabel lbl_sil_mesaj;
    private javax.swing.JPasswordField pwfield;
    private javax.swing.JTable tb_cezalar;
    private javax.swing.JTable tb_sil;
    private javax.swing.JTable tb_users;
    private javax.swing.JTextField tf_ad;
    private javax.swing.JTextField tf_soyad;
    private javax.swing.JTextField tf_tckn;
    // End of variables declaration//GEN-END:variables
}
